### ISSUE TITLE
Error while running Python 3.10

### ISSUE THREAD

**Issue by catchthewind** [vinaypundith/bettercamp#7]
I installed Windows 11 PRO Version: 10.0.19041.3636 and then Python 3.10
Tried BootCamp folder in bettercamp-main as well as in root of USB
I have Bootcamp 4.0.4033

Every time I run your script I get first step done and then error :(
Can you tell me what could be wrong with it?

OUtput and error below:

Python 3.10.0 (tags/v3.10.0:b494f59, Oct 4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.

=================== RESTART: D:\bettercamp-main\bettercamp.py ==================
MacBookPro5,3
EFI boot mode detected
Installing Chainloader to patch nVidia graphics driver bootloop/blank screen when booting in EFI mode
Traceback (most recent call last):
File "D:\bettercamp-main\bettercamp.py", line 109, in
run_boot_camp_installer()
File "D:\bettercamp-main\bettercamp.py", line 39, in run_boot_camp_installer
bcversion = float(bcversionstring[bcversionstring.find('')+16:bcversionstring.find('CC1222222222222222222222222222222222222222222222222222222222222222222222222222222222222222P')+19])
ValueError: could not convert string to float: ''

**Comment by catchthewind** [comment]
I have also run linux to check the IDs of GF 9400

line with display has ID
pci@0000:03:00.0    display  C79 [Geforce 9400M]

line with bridge right BEFORE display has ID
pci@0000:00:10.0  bridge MCP79 PCI Express Bridge


Please tell how to fix script error above and also what to put into startup.nsh ??

Thanks

**Comment by rondog86** [comment]
other question... where do I get the Autounattend.xml? it says in this repository but I cant find it

**Comment by H1inne4ma** [comment]
Same error diffrent machine 
MacBook Pro 5,4 15 Inch

MacBookPro5,4
EFI boot mode detected
Installing Chainloader to patch nVidia graphics driver bootloop/blank screen when booting in EFI mode
Traceback (most recent call last):
  File "E:\bettercamp-main\bettercamp.py", line 109, in <module>
    run_boot_camp_installer()
  File "E:\bettercamp-main\bettercamp.py", line 39, in run_boot_camp_installer
    bcversion = float(bcversionstring[bcversionstring.find('<ProductVersion>')+16:bcversionstring.find('<ProductVersion>CC1222222222222222222222222222222222222222222222222222222222222222222222222222222222222222P')+19])
ValueError: could not convert string to float: ''

**Comment by H1inne4ma** [comment]
Didnt matter, the fix was installed anyway. But with wrong parameters for the machine i am using.

This is my startup.nsh now:
mm 0010003E 1 ;PCI :8
mm 03000004 1 ;PCI :7
fs0:\EFI\Microsoft\Boot\bootmgfw.efi

**Comment by vinaypundith** [comment]
What machine do you have? @H1inne4ma I can try to gather the parameters for more models
